name: FRC Build & Test
on: [push, pull_request]
  # branches:
  #     - main
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2-beta
    - name: FRC Build & Test
      uses: actions/setup-java@v2
          with:
            java-version: '7'
            distribution: 'adopt'
      uses: 4201VitruvianBots/FRC-actions@v1
      with:
        build_mode: 'build'
